version: '3'

services:
  app:
    container_name: php7.4_apache
    build: ./docker/app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"

  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=lumen_db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_ROOT_PASSWORD=root

    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root

    depends_on:
      - db
    ports:
      - "8081:80"
